services:
  - type: web
    name: novatech-app
    runtime: java
    javaVersion: "21"
    buildCommand: "./mvnw clean package -DskipTests"
    startCommand: "java -Dspring.profiles.active=prod -jar target/service-app-0.0.1-SNAPSHOT.jar"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: novatech-db
          property: connectionString

      - key: DB_USERNAME
        fromDatabase:
          name: novatech-db
          property: user

      - key: DB_PASSWORD
        fromDatabase:
          name: novatech-db
          property: password

      - key: APP_DOMAIN
        value: pratiktech.cloud

      - key: APP_SCHEME
        value: https

      - key: APP_PORT
        value: "443"

      - key: PORT
        value: "8080"

      - key: SUPERADMIN_EMAIL
        sync: false

      - key: SUPERADMIN_PASSWORD
        sync: false

      - key: SPRING_PROFILES_ACTIVE
        value: prod

  - type: pserv
    name: novatech-db
    ipWhitelist: []
    plan: standard
    postgresVersion: "14"